# Site settings
title: 王文超's blog
email: 
description: "老实人"
baseurl: ""
url: "http://arcsecw.github.io"
twitter_username: arcsecw
github_username:  arcsecw

# Build settings
markdown: kramdown
permalink: pretty

highlighter: rouge
kramdown:
  input: GFM
  auto_ids: true
  syntax_highlighter: rouge
